# Generated by Django 4.0.1 on 2022-02-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eth',
            name='balance',
            field=models.FloatField(),
        ),
    ]
